# Generated by Django 3.2.6 on 2023-04-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_allotment', '0002_auto_20230411_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
    ]
