# Generated by Django 3.2.6 on 2023-04-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_allotment', '0003_remove_student_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
