# Generated by Django 3.2.6 on 2023-04-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_allotment', '0007_auto_20230411_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
