# Generated by Django 3.2.6 on 2023-04-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_allotment', '0006_auto_20230411_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='yearOfStudy',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
